# Generated by Django 4.2.11 on 2026-02-28 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloudfile',
            name='category',
            field=models.CharField(choices=[('music', 'Music'), ('video', 'Video'), ('document', 'Document'), ('photo', 'Photo'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
